services:

  server:
    image: smallstep/step-ca:${STEPCA_TAG:-latest}
    restart: ${RESTART:-unless-stopped}
    logging:
      driver: ${LOGGING_DRIVER:-local}
    ports:
      - ${STEPCA_PORT:-9000}:9000
    volumes:
      - ${DATA_DIR:-data}:/home/step
    env_file: .env

  fingerprint:
    image: smallstep/step-ca:${STEPCA_TAG:-latest}
    command: step certificate fingerprint certs/root_ca.crt
    volumes:
      - ${DATA_DIR:-data}:/home/step
    depends_on:
      - server

volumes:
  data: